### ISSUE TITLE
What does '-s' mean in a parameter

### ISSUE THREAD

**Issue by floydawong** [Koihik/sublime-lua-format#2]
`command = "'" + command + "' -si '" + self.filename + "'"`

我是另一个[LuaFormat](https://github.com/floydawong/LuaFormat)插件的作者.
我那个插件功能上有缺陷, 而且只支持sublime和python.
所以我打算优化一下你这个仓库.

时间有限, 没去看源码, 所以直接开口问问这个`si`参数是个啥意思:)

**Comment by Koihik** [comment]
read from standard input stream instead of read from file.

**Comment by floydawong** [comment]
tks, i got it~
